---
- name: Configure Router, HW-RT
  hosts: router1
  gather_facts: no

  tasks:
  - name: Configure hostname
    cisco.ios.ios_hostname:
      config:
        hostname: HW-RT
      state: merged

  - name: Configure VLANs
    cisco.ios.ios_vlans:
      config:
        - name: Beheer
          vlan_id: 10
          state: active
        - name: Werknemers
          vlan_id: 11
          state: active
        - name: Studenten
          vlan_id: 12
          state: active
        - name: DataCentrum
          vlan_id: 13
          state: active
        - name: ISP
          vlan_id: 14
          state: active
      state: merged