---
- name: Configure Router, NS-RT
  hosts: router2
  gather_facts: no

  tasks:
  - name: Configure hostname
    cisco.ios.ios_hostname:
      config:
        hostname: NS-RT
      state: merged

  - name: Configure VLANs
    cisco.ios.ios_vlans:
      config:
        - name: Werknemers
          vlan_id: 20
          state: active
        - name: Studenten
          vlan_id: 21
          state: active
      state: merged