---
- name: Configure Router, NS-RT
  hosts: router2
  gather_facts: no

  tasks:
    - name: Configure hostname
      cisco.ios.ios_hostname:
        config:
          hostname: NS-RT
        state: merged

    - name: Configure VLANs
      cisco.ios.ios_vlans:
        config:
          - name: Medewerkers
            vlan_id: 20
            state: active
          - name: Studenten
            vlan_id: 21
            state: active
        state: merged

    - name: Configure VLAN interfaces
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Vlan20
            ipv4:
              - address: 10.2.0.1/24
          - name: Vlan21
            ipv4:
              - address: 10.2.1.1/24

    - name: Save all configurations
      cisco.ios.ios_command:
        commands:
          - write memory