---
- name: Configure Switch 2, HW-SW2
  hosts: switch2
  gather_facts: no

  tasks:
    - name: Configure hostname
      cisco.ios.ios_hostname:
        config:
          hostname: HW-SW2
        state: merged

    - name: Configure VLANs
      cisco.ios.ios_vlans:
        config:
          - name: Beheer
            vlan_id: 10
            state: active
          - name: Medewerkers
            vlan_id: 11
            state: active
          - name: Studenten
            vlan_id: 12
            state: active
          - name: DataCentrum
            vlan_id: 13
            state: active
        state: merged

    - name: Configure L2 interfaces
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1
            mode: trunk
            trunk:
              allowed_vlans: 10-13
          - name: GigabitEthernet2
            mode: trunk
            trunk:
              allowed_vlans: 10-13
          - name: GigabitEthernet3
            mode: trunk
            trunk:
              allowed_vlans: 10-12
          - name: GigabitEthernet4
            mode: access
            access:
              vlan: 10
          - name: GigabitEthernet5
            mode: access
            access:
              vlan: 11
          - name: GigabitEthernet6
            mode: access
            access:
              vlan: 11
          - name: GigabitEthernet7
            mode: access
            access:
              vlan: 12
          - name: GigabitEthernet8
            mode: access
            access:
              vlan: 12
          - name: GigabitEthernet9
            mode: access
            access:
              vlan: 13
          - name: GigabitEthernet10
            mode: access
            access:
              vlan: 13
        state: merged

    - name: Configure Multiple Spanning-Tree Protocol (MSTP)
      cisco.ios.ios_config:
        lines:
          - spanning-tree mode mst
          - spanning-tree mst configuration
          - revision 1
          - name Universiteit Harderwijk
          - instance 1 vlan 10,11,12,13
          - exit
          - spanning-tree mst 1 priority 8192
          - end

    - name: Save all configurations
      cisco.ios.ios_command:
        commands:
          - write memory